### ISSUE TITLE
INFOGRAFIA MULTI-HILOS

### ISSUE THREAD

**Issue by ang3-l32** [SistemasTecTlaxiaco/infografia-de-hilos-ang3-l32#2]
[INFOGRAFIA HILOS.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-ang3-l32/files/8852885/INFOGRAFIA.HILOS.pdf)

**Comment by abicoronel** [comment]
calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
